settings:
  translate: true
  token: "TOKEN"
  activity: "MtG Tournament Manager 2020"
  name: Trostani
  prefix: "!"
  builder:
    kind: "manastack"
    url: "https://manastack.com"
    username: "email@example.com"
    password: "p4ssw0rd"
    profile: "example"
  challonge:
    key: "KEY"
    channels:
      - "ID"
    roles:
      - "role"
    parent: "ID"
  push:
    channels:
      - "ID"
